module.exports = {
  apps: [
    {
      name: 'elite-backend',
      cwd: __dirname,
      script: 'server/start.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      min_uptime: '10s',
      restart_delay: 3000,
      out_file: '/var/log/elite-backend/out.log',
      error_file: '/var/log/elite-backend/error.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT || 3306,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_NAME: process.env.DB_NAME || 'EliteTobacco',
        DB_CONNECTION_LIMIT: process.env.DB_CONNECTION_LIMIT || 10,
        DB_AUTO_CREATE: process.env.DB_AUTO_CREATE || 'false',
        DB_CLEAN_SETUP: process.env.DB_CLEAN_SETUP || 'false',
      },
    },
  ],
};
