// src/styles.js  –  shared style tokens

export const S = {
  app: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #fff1f3 0%, #ffe5d9 100%)',
    fontFamily: 'Roboto',
    fontWeight: 700,
    color: '#1a1a1a',
  },
  topBar: {
    background: '#fff',
    borderBottom: '3px solid #e63946',
    padding: '10px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 4px 14px rgba(228, 233, 185, 0.18)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  topBarTitle: { fontSize: 18, fontWeight: 800, color: '#d62839', letterSpacing: 1 },
  buyerInfo:   { display: 'flex', gap: 20, alignItems: 'center', fontSize: 14, flexWrap: 'wrap' },
  buyerBadge:  { background: '#ffe3e6', border: '1px solid #ff9aa2', borderRadius: 8, padding: '4px 12px', fontWeight: 800, color: 'darkblue', fontSize: 14 },
  bagsBadge:   { background: '#ffe3e6', color: 'dark blue', borderRadius: 20, padding: '3px 12px', fontSize: 13, fontWeight: 800 },
  page:        { maxWidth: 946, margin: '0 auto', padding: '24px 16px' },
  card:        { background: '#ffffff', borderRadius: 12, border: '1px solid #ffd0d6', padding: '24px', marginBottom: 20, boxShadow: '0 4px 16px rgba(230,57,70,0.12)' },
  heading:     { fontSize: 22, fontWeight: 800, color: '#d62839', marginBottom: 20, letterSpacing: 0.5 },
  subheading:  { fontSize: 16, fontWeight: 800, color: '#d62839', marginBottom: 12 },
  label:       { fontSize: 12, fontWeight: 800, color: '#4a4a4a', marginBottom: 5, display: 'block', textTransform: 'uppercase', letterSpacing: 0.5 },
  input:       { width: '100%', padding: '10px 14px', border: '1.5px solid #ffb3c1', borderRadius: 8, fontSize: 15, fontWeight: 700, color: '#1a1a1a', background: '#fff7f8', boxSizing: 'border-box', outline: 'none' },
  row:         { marginBottom: 18 },
  toggleGroup: { display: 'flex', gap: 0, borderRadius: 8, overflow: 'hidden', border: '1.5px solid #e63946', marginBottom: 6 },
  toggleBtn: (active, disabled) => ({
    flex: 1, padding: '12px', border: 'none',
    background: disabled ? '#f0f0f0' : active ? '#ffdfe4' : '#fff',
    color: disabled ? '#bbb' : '#d62839',
    fontWeight: 800, fontSize: 15,
    cursor: disabled ? 'not-allowed' : 'pointer',
    letterSpacing: 1, transition: 'all 0.2s',
    pointerEvents: disabled ? 'none' : 'auto',
  }),
  btnPrimary:  { background: '#e63946', color: '#fff', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 15, fontWeight: 800, cursor: 'pointer', flex: 1, transition: 'background 0.2s' },
  btnSecondary:{ background: '#fff', color: '#d62839', border: '2px solid #e63946', borderRadius: 8, padding: '12px 24px', fontSize: 15, fontWeight: 800, cursor: 'pointer', flex: 1 },
  btnIcon:     { background: '#fff0f2', border: '1px solid #ffc2cc', borderRadius: 6, padding: '4px 12px', cursor: 'pointer', fontSize: 12, color: '#d62839', fontWeight: 800 },
  btnRow:      { display: 'flex', gap: 12, marginTop: 24 },
  error:       { background: '#fff0f2', border: '1px solid #ffb3bf', borderRadius: 8, padding: '10px 14px', color: '#d62839', fontSize: 13, fontWeight: 800, marginBottom: 14 },
  success:     { background: '#ebfff1', border: '1px solid #8fd9a8', borderRadius: 8, padding: '10px 14px', color: '#1f7a3d', fontSize: 13, fontWeight: 800, marginBottom: 14 },
  table:       { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th:          { background: '#ffe8ec', color: '#d62839', fontWeight: 800, padding: '10px 12px', border: '1px solid #ffd0d6', textAlign: 'left', textTransform: 'uppercase', fontSize: 11, letterSpacing: 0.5 },
  td:          { padding: '9px 12px', border: '1px solid #ffe2e7', color: '#2b2b2b', verticalAlign: 'middle', fontWeight: 700 },
  badge: (color) => ({
    display: 'inline-block', padding: '2px 10px', borderRadius: 20, fontSize: 11, fontWeight: 800,
    background: color === 'green' ? '#dff8e8' : color === 'red' ? '#ffdfe4' : '#f5f5f5',
    color: color === 'green' ? '#1f7a3d' : color === 'red' ? '#d62839' : '#666',
  }),
  tabs:       { display: 'flex', gap: 8, marginBottom: 24, flexWrap: 'wrap' },
  tab: (active) => ({
    padding: '10px 20px',
    border: active ? '2px solid #e63946' : '2px solid #ddd',
    borderRadius: 8,
    background: active ? '#e63946' : '#fff',
    color: active ? '#fff' : '#555',
    fontWeight: 800, fontSize: 14, cursor: 'pointer',
    letterSpacing: 0.3, whiteSpace: 'nowrap',
    transition: 'all 0.18s',
  }),
  qrGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 16, marginTop: 16 },
  qrCard: { background: '#fff', border: '1.5px solid #ffd0d6', borderRadius: 10, padding: 14, textAlign: 'center', boxShadow: '0 4px 10px rgba(230,57,70,0.12)' },
};
