// src/styles.js  –  shared style tokens

export const S = {
  app: {
    minHeight: '100vh',
    background: '#fdf5f5',
    fontFamily: "'Georgia', 'Times New Roman', serif",
    color: '#1a1a1a',
  },
  topBar: {
    background: '#fff',
    borderBottom: '2px solid #c0392b',
    padding: '10px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 2px 8px rgba(192,57,43,0.08)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  topBarTitle: { fontSize: 18, fontWeight: 'bold', color: '#c0392b', letterSpacing: 1 },
  buyerInfo:   { display: 'flex', gap: 20, alignItems: 'center', fontSize: 14, flexWrap: 'wrap' },
  buyerBadge:  { background: '#fdf0ee', border: '1px solid #e0b0a8', borderRadius: 8, padding: '4px 12px', fontWeight: 'bold', color: '#c0392b', fontSize: 14 },
  bagsBadge:   { background: '#c0392b', color: 'white', borderRadius: 20, padding: '3px 12px', fontSize: 13, fontWeight: 'bold' },
  page:        { maxWidth: 860, margin: '0 auto', padding: '24px 16px' },
  card:        { background: '#fff', borderRadius: 12, border: '1px solid #f0dada', padding: '24px', marginBottom: 20, boxShadow: '0 2px 12px rgba(192,57,43,0.06)' },
  heading:     { fontSize: 22, fontWeight: 'bold', color: '#c0392b', marginBottom: 20, letterSpacing: 0.5 },
  subheading:  { fontSize: 16, fontWeight: 'bold', color: '#c0392b', marginBottom: 12 },
  label:       { fontSize: 12, fontWeight: 'bold', color: '#666', marginBottom: 5, display: 'block', textTransform: 'uppercase', letterSpacing: 0.5 },
  input:       { width: '100%', padding: '10px 14px', border: '1.5px solid #e8c4be', borderRadius: 8, fontSize: 15, color: '#1a1a1a', background: '#fffafa', boxSizing: 'border-box', outline: 'none' },
  row:         { marginBottom: 18 },
  toggleGroup: { display: 'flex', gap: 0, borderRadius: 8, overflow: 'hidden', border: '1.5px solid #c0392b', marginBottom: 6 },
  toggleBtn: (active, disabled) => ({
    flex: 1, padding: '12px', border: 'none',
    background: disabled ? '#f0f0f0' : active ? '#fde8e5' : '#fff',
    color: disabled ? '#bbb' : '#c0392b',
    fontWeight: 'bold', fontSize: 15,
    cursor: disabled ? 'not-allowed' : 'pointer',
    letterSpacing: 1, transition: 'all 0.2s',
    pointerEvents: disabled ? 'none' : 'auto',
  }),
  btnPrimary:  { background: '#c0392b', color: '#fff', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 15, fontWeight: 'bold', cursor: 'pointer', flex: 1, transition: 'background 0.2s' },
  btnSecondary:{ background: '#fff', color: '#c0392b', border: '2px solid #c0392b', borderRadius: 8, padding: '12px 24px', fontSize: 15, fontWeight: 'bold', cursor: 'pointer', flex: 1 },
  btnIcon:     { background: 'none', border: '1px solid #ddd', borderRadius: 6, padding: '4px 12px', cursor: 'pointer', fontSize: 12, color: '#888' },
  btnRow:      { display: 'flex', gap: 12, marginTop: 24 },
  error:       { background: '#fff0ee', border: '1px solid #f5c0b8', borderRadius: 8, padding: '10px 14px', color: '#c0392b', fontSize: 13, marginBottom: 14 },
  success:     { background: '#f0fff4', border: '1px solid #b2dfdb', borderRadius: 8, padding: '10px 14px', color: '#2e7d32', fontSize: 13, marginBottom: 14 },
  table:       { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th:          { background: '#fdf0ee', color: '#c0392b', fontWeight: 'bold', padding: '10px 12px', border: '1px solid #f0dada', textAlign: 'left', textTransform: 'uppercase', fontSize: 11, letterSpacing: 0.5 },
  td:          { padding: '9px 12px', border: '1px solid #f5e8e6', color: '#333', verticalAlign: 'middle' },
  badge: (color) => ({
    display: 'inline-block', padding: '2px 10px', borderRadius: 20, fontSize: 11, fontWeight: 'bold',
    background: color === 'green' ? '#e8f5e9' : color === 'red' ? '#fde8e5' : '#f5f5f5',
    color: color === 'green' ? '#2e7d32' : color === 'red' ? '#c0392b' : '#666',
  }),
  tabs:       { display: 'flex', gap: 0, borderBottom: '2px solid #f0dada', marginBottom: 24, flexWrap: 'wrap' },
  tab: (active) => ({
    padding: '10px 18px', border: 'none', background: 'none',
    color: active ? '#c0392b' : '#888',
    fontWeight: active ? 'bold' : 'normal', fontSize: 14, cursor: 'pointer',
    borderBottom: active ? '3px solid #c0392b' : '3px solid transparent',
    marginBottom: -2, letterSpacing: 0.3, whiteSpace: 'nowrap',
  }),
  qrGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 16, marginTop: 16 },
  qrCard: { background: '#fff', border: '1.5px solid #f0dada', borderRadius: 10, padding: 14, textAlign: 'center', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' },
};
